"""Mock provider dataset for Karachi areas.

Each provider includes coordinates and areas for distance computation.
"""

from __future__ import annotations

# Centroids (lat, lng) for Karachi areas as defined in the request prompt.
# Used by tools.find_providers to compute distance_km between user and provider.
KARACHI_COORDS: dict[str, tuple[float, float]] = {
    "DHA Phase 6": (24.7920, 67.0645),
    "DHA Phase 2": (24.8104, 67.0657),
    "Clifton Block 5": (24.8090, 67.0307),
    "Clifton Block 8": (24.8207, 67.0254),
    "Gulshan-e-Iqbal Block 13": (24.9197, 67.1134),
    "Gulshan-e-Iqbal Block 7": (24.9253, 67.1005),
    "PECHS Block 2": (24.8654, 67.0590),
    "PECHS Block 6": (24.8694, 67.0635),
    "North Nazimabad Block H": (24.9439, 67.0505),
    "North Nazimabad Block J": (24.9476, 67.0549),
    "Nazimabad No.3": (24.9237, 67.0317),
    "Bahadurabad": (24.8787, 67.0639),
    "Tariq Road": (24.8638, 67.0653),
    "Federal B Area Block 4": (24.9304, 67.0697),
    "Malir Cantonment": (24.8936, 67.2002),
    "Korangi": (24.8296, 67.1282),
    "Landhi": (24.8554, 67.2012),
    "Orangi Town": (24.9604, 67.0018),
    "Surjani Town": (25.0165, 67.0416),
    "Saddar": (24.8607, 67.0099),
}

MOCK_PROVIDERS: list[dict] = [
    # ---- AC Technicians (6) ----------------------------------------------------
    {
        "id": "ac_001",
        "name": "Arctic Cool AC Services",
        "category": "ac_technician",
        "area": "DHA Phase 6",
        "lat": 24.7920,
        "lng": 67.0645,
        "rating": 4.8,
        "availability": "tomorrow 10:00 AM",
        "on_time_score": 0.96,
        "cancellation_rate": 0.02,
        "review_count": 154,
        "specializations": ["Split AC", "Inverter AC Repair", "AC Gas Refill"],
        "base_fee_pkr": 600,
        "per_hour_pkr": 400,
        "years_experience": 8,
        "phone": "0312-5551234",
    },
    {
        "id": "ac_002",
        "name": "CoolBreeze AC Repair",
        "category": "ac_technician",
        "area": "Clifton Block 5",
        "lat": 24.8090,
        "lng": 67.0307,
        "rating": 4.7,
        "availability": "tomorrow 11:30 AM",
        "on_time_score": 0.94,
        "cancellation_rate": 0.03,
        "review_count": 112,
        "specializations": ["Window AC", "Split AC", "General Service"],
        "base_fee_pkr": 500,
        "per_hour_pkr": 300,
        "years_experience": 5,
        "phone": "0333-4445678",
    },
    {
        "id": "ac_003",
        "name": "Al-Rehman AC Works",
        "category": "ac_technician",
        "area": "Gulshan-e-Iqbal Block 13",
        "lat": 24.9197,
        "lng": 67.1134,
        "rating": 4.5,
        "availability": "today 5:00 PM",
        "on_time_score": 0.91,
        "cancellation_rate": 0.05,
        "review_count": 89,
        "specializations": ["Cassette AC", "Split AC", "Compressor Replacement"],
        "base_fee_pkr": 700,
        "per_hour_pkr": 500,
        "years_experience": 10,
        "phone": "0345-2223344",
    },
    {
        "id": "ac_004",
        "name": "SnowFlake Technicians",
        "category": "ac_technician",
        "area": "PECHS Block 2",
        "lat": 24.8654,
        "lng": 67.0590,
        "rating": 4.6,
        "availability": "tomorrow 09:00 AM",
        "on_time_score": 0.95,
        "cancellation_rate": 0.04,
        "review_count": 76,
        "specializations": ["Inverter AC", "Gas Leakage Fixing"],
        "base_fee_pkr": 550,
        "per_hour_pkr": 350,
        "years_experience": 6,
        "phone": "0321-9876543",
    },
    {
        "id": "ac_005",
        "name": "Karachi Air Solutions",
        "category": "ac_technician",
        "area": "North Nazimabad Block H",
        "lat": 24.9439,
        "lng": 67.0505,
        "rating": 4.4,
        "availability": "tomorrow 02:00 PM",
        "on_time_score": 0.89,
        "cancellation_rate": 0.06,
        "review_count": 120,
        "specializations": ["Split AC Installation", "AC Dismantling"],
        "base_fee_pkr": 500,
        "per_hour_pkr": 300,
        "years_experience": 7,
        "phone": "0300-1122334",
    },
    {
        "id": "ac_006",
        "name": "Super Chiller AC",
        "category": "ac_technician",
        "area": "Saddar",
        "lat": 24.8607,
        "lng": 67.0099,
        "rating": 4.3,
        "availability": "today 7:00 PM",
        "on_time_score": 0.88,
        "cancellation_rate": 0.07,
        "review_count": 94,
        "specializations": ["Commercial AC Repair", "Window AC Repair"],
        "base_fee_pkr": 600,
        "per_hour_pkr": 450,
        "years_experience": 9,
        "phone": "0313-4455667",
    },

    # ---- Plumbers (6) ----------------------------------------------------------
    {
        "id": "plumb_001",
        "name": "Hassan Plumbing Services",
        "category": "plumber",
        "area": "PECHS Block 6",
        "lat": 24.8694,
        "lng": 67.0635,
        "rating": 4.8,
        "availability": "tomorrow 10:00 AM",
        "on_time_score": 0.97,
        "cancellation_rate": 0.01,
        "review_count": 210,
        "specializations": ["Leak Repair", "Bathroom Fitting", "Water Pump Repair"],
        "base_fee_pkr": 400,
        "per_hour_pkr": 250,
        "years_experience": 12,
        "phone": "0333-8889900",
    },
    {
        "id": "plumb_002",
        "name": "AquaFix Plumbers",
        "category": "plumber",
        "area": "Clifton Block 8",
        "lat": 24.8207,
        "lng": 67.0254,
        "rating": 4.6,
        "availability": "tomorrow 01:00 PM",
        "on_time_score": 0.93,
        "cancellation_rate": 0.04,
        "review_count": 145,
        "specializations": ["Pipeline Unblocking", "Kitchen Sink Repair"],
        "base_fee_pkr": 500,
        "per_hour_pkr": 300,
        "years_experience": 6,
        "phone": "0322-7776655",
    },
    {
        "id": "plumb_003",
        "name": "Al-Madina Plumbing",
        "category": "plumber",
        "area": "Gulshan-e-Iqbal Block 7",
        "lat": 24.9253,
        "lng": 67.1005,
        "rating": 4.5,
        "availability": "today 6:00 PM",
        "on_time_score": 0.90,
        "cancellation_rate": 0.05,
        "review_count": 98,
        "specializations": ["Geyser Repair", "Water Tank Cleaning"],
        "base_fee_pkr": 450,
        "per_hour_pkr": 250,
        "years_experience": 8,
        "phone": "0346-1234567",
    },
    {
        "id": "plumb_004",
        "name": "Quick Fix Plumbers",
        "category": "plumber",
        "area": "Bahadurabad",
        "lat": 24.8787,
        "lng": 67.0639,
        "rating": 4.7,
        "availability": "tomorrow 09:30 AM",
        "on_time_score": 0.95,
        "cancellation_rate": 0.02,
        "review_count": 118,
        "specializations": ["Taps & Showers Repair", "Drain Blockage Cleaning"],
        "base_fee_pkr": 500,
        "per_hour_pkr": 300,
        "years_experience": 7,
        "phone": "0312-3334445",
    },
    {
        "id": "plumb_005",
        "name": "Nazimabad Plumbing Solutions",
        "category": "plumber",
        "area": "Nazimabad No.3",
        "lat": 24.9237,
        "lng": 67.0317,
        "rating": 4.4,
        "availability": "tomorrow 03:00 PM",
        "on_time_score": 0.88,
        "cancellation_rate": 0.06,
        "review_count": 64,
        "specializations": ["Pipe Repair", "Sewer Line Unclogging"],
        "base_fee_pkr": 350,
        "per_hour_pkr": 200,
        "years_experience": 5,
        "phone": "0300-8887766",
    },
    {
        "id": "plumb_006",
        "name": "Korangi Aqua Experts",
        "category": "plumber",
        "area": "Korangi",
        "lat": 24.8296,
        "lng": 67.1282,
        "rating": 4.3,
        "availability": "today 4:00 PM",
        "on_time_score": 0.85,
        "cancellation_rate": 0.08,
        "review_count": 52,
        "specializations": ["Water Motor Fixing", "Underground Leakage Detection"],
        "base_fee_pkr": 400,
        "per_hour_pkr": 250,
        "years_experience": 6,
        "phone": "0315-9988776",
    },

    # ---- Electricians (6) ----------------------------------------------------
    {
        "id": "elec_001",
        "name": "Bright Spark Electricians",
        "category": "electrician",
        "area": "DHA Phase 2",
        "lat": 24.8104,
        "lng": 67.0657,
        "rating": 4.9,
        "availability": "tomorrow 10:00 AM",
        "on_time_score": 0.98,
        "cancellation_rate": 0.01,
        "review_count": 182,
        "specializations": ["Short Circuit Fixing", "DB Box Installation", "UPS Service"],
        "base_fee_pkr": 500,
        "per_hour_pkr": 300,
        "years_experience": 11,
        "phone": "0331-5556677",
    },
    {
        "id": "elec_002",
        "name": "PowerLine Solutions",
        "category": "electrician",
        "area": "Tariq Road",
        "lat": 24.8638,
        "lng": 67.0653,
        "rating": 4.7,
        "availability": "tomorrow 02:30 PM",
        "on_time_score": 0.94,
        "cancellation_rate": 0.03,
        "review_count": 139,
        "specializations": ["Ceiling Fan Repair", "House Wiring", "Chandelier Installation"],
        "base_fee_pkr": 450,
        "per_hour_pkr": 250,
        "years_experience": 8,
        "phone": "0323-2221199",
    },
    {
        "id": "elec_003",
        "name": "Al-Noor Electric",
        "category": "electrician",
        "area": "Federal B Area Block 4",
        "lat": 24.9304,
        "lng": 67.0697,
        "rating": 4.6,
        "availability": "today 6:30 PM",
        "on_time_score": 0.92,
        "cancellation_rate": 0.04,
        "review_count": 91,
        "specializations": ["Washing Machine Repair", "Generator Overhauling"],
        "base_fee_pkr": 400,
        "per_hour_pkr": 200,
        "years_experience": 9,
        "phone": "0345-3337777",
    },
    {
        "id": "elec_004",
        "name": "North Karachi Power Sparks",
        "category": "electrician",
        "area": "North Nazimabad Block J",
        "lat": 24.9476,
        "lng": 67.0549,
        "rating": 4.5,
        "availability": "tomorrow 11:00 AM",
        "on_time_score": 0.91,
        "cancellation_rate": 0.05,
        "review_count": 87,
        "specializations": ["Smart Switch Installation", "AC Socket Repair"],
        "base_fee_pkr": 450,
        "per_hour_pkr": 250,
        "years_experience": 6,
        "phone": "0313-9998888",
    },
    {
        "id": "elec_005",
        "name": "Malir Electric Hub",
        "category": "electrician",
        "area": "Malir Cantonment",
        "lat": 24.8936,
        "lng": 67.2002,
        "rating": 4.4,
        "availability": "tomorrow 04:00 PM",
        "on_time_score": 0.89,
        "cancellation_rate": 0.05,
        "review_count": 68,
        "specializations": ["Solar Inverter Setup", "Light Fittings"],
        "base_fee_pkr": 600,
        "per_hour_pkr": 300,
        "years_experience": 7,
        "phone": "0300-5553322",
    },
    {
        "id": "elec_006",
        "name": "Saddar Electronics Repair",
        "category": "electrician",
        "area": "Saddar",
        "lat": 24.8607,
        "lng": 67.0099,
        "rating": 4.2,
        "availability": "today 8:00 PM",
        "on_time_score": 0.86,
        "cancellation_rate": 0.08,
        "review_count": 105,
        "specializations": ["Microwave Oven Repair", "UPS Battery Replacement"],
        "base_fee_pkr": 400,
        "per_hour_pkr": 300,
        "years_experience": 10,
        "phone": "0332-1110000",
    },

    # ---- Carpenters (6) --------------------------------------------------------
    {
        "id": "carp_001",
        "name": "Master Craft Furniture",
        "category": "carpenter",
        "area": "Gulshan-e-Iqbal Block 13",
        "lat": 24.9197,
        "lng": 67.1134,
        "rating": 4.8,
        "availability": "tomorrow 10:00 AM",
        "on_time_score": 0.96,
        "cancellation_rate": 0.02,
        "review_count": 143,
        "specializations": ["Door Repair", "Sofa Polishing", "Cabinet Making"],
        "base_fee_pkr": 600,
        "per_hour_pkr": 350,
        "years_experience": 15,
        "phone": "0334-2228888",
    },
    {
        "id": "carp_002",
        "name": "Woodworks Karachi",
        "category": "carpenter",
        "area": "DHA Phase 6",
        "lat": 24.7920,
        "lng": 67.0645,
        "rating": 4.7,
        "availability": "tomorrow 02:00 PM",
        "on_time_score": 0.94,
        "cancellation_rate": 0.03,
        "review_count": 102,
        "specializations": ["Lock Replacement", "Wooden Flooring Repair", "Kitchen Cabinet Fix"],
        "base_fee_pkr": 700,
        "per_hour_pkr": 400,
        "years_experience": 9,
        "phone": "0321-4447777",
    },
    {
        "id": "carp_003",
        "name": "Al-Hamza Carpentry",
        "category": "carpenter",
        "area": "Bahadurabad",
        "lat": 24.8787,
        "lng": 67.0639,
        "rating": 4.6,
        "availability": "today 4:30 PM",
        "on_time_score": 0.92,
        "cancellation_rate": 0.04,
        "review_count": 83,
        "specializations": ["Bed Assembly", "Table Customization", "Wood Hinge Fix"],
        "base_fee_pkr": 500,
        "per_hour_pkr": 300,
        "years_experience": 7,
        "phone": "0344-9993333",
    },
    {
        "id": "carp_004",
        "name": "PECHS Fine Woods",
        "category": "carpenter",
        "area": "PECHS Block 2",
        "lat": 24.8654,
        "lng": 67.0590,
        "rating": 4.5,
        "availability": "tomorrow 09:00 AM",
        "on_time_score": 0.91,
        "cancellation_rate": 0.05,
        "review_count": 71,
        "specializations": ["Wardrobe Repair", "Drawer Rail Fixing"],
        "base_fee_pkr": 500,
        "per_hour_pkr": 300,
        "years_experience": 6,
        "phone": "0301-4455888",
    },
    {
        "id": "carp_005",
        "name": "Nazimabad Wood Creations",
        "category": "carpenter",
        "area": "Nazimabad No.3",
        "lat": 24.9237,
        "lng": 67.0317,
        "rating": 4.4,
        "availability": "tomorrow 12:00 PM",
        "on_time_score": 0.89,
        "cancellation_rate": 0.06,
        "review_count": 59,
        "specializations": ["Door Polish", "Wooden Bench Repair"],
        "base_fee_pkr": 400,
        "per_hour_pkr": 250,
        "years_experience": 8,
        "phone": "0316-2221111",
    },
    {
        "id": "carp_006",
        "name": "Orangi Wood Masters",
        "category": "carpenter",
        "area": "Orangi Town",
        "lat": 24.9604,
        "lng": 67.0018,
        "rating": 4.2,
        "availability": "today 6:00 PM",
        "on_time_score": 0.87,
        "cancellation_rate": 0.07,
        "review_count": 48,
        "specializations": ["Door Fitting", "Simple Wood Repair"],
        "base_fee_pkr": 300,
        "per_hour_pkr": 200,
        "years_experience": 5,
        "phone": "0300-3331122",
    },

    # ---- Painters (6) ----------------------------------------------------------
    {
        "id": "paint_001",
        "name": "ColorMax Painters",
        "category": "painter",
        "area": "Clifton Block 5",
        "lat": 24.8090,
        "lng": 67.0307,
        "rating": 4.8,
        "availability": "tomorrow 10:00 AM",
        "on_time_score": 0.95,
        "cancellation_rate": 0.02,
        "review_count": 124,
        "specializations": ["Wall Painting", "Texture Wall Art", "Damp Protection Treatment"],
        "base_fee_pkr": 800,
        "per_hour_pkr": 400,
        "years_experience": 10,
        "phone": "0321-5559988",
    },
    {
        "id": "paint_002",
        "name": "Brush & Roll Services",
        "category": "painter",
        "area": "DHA Phase 2",
        "lat": 24.8104,
        "lng": 67.0657,
        "rating": 4.7,
        "availability": "tomorrow 01:00 PM",
        "on_time_score": 0.93,
        "cancellation_rate": 0.03,
        "review_count": 93,
        "specializations": ["Interior Paint", "Exterior Paint", "Sticker Wall Application"],
        "base_fee_pkr": 700,
        "per_hour_pkr": 350,
        "years_experience": 7,
        "phone": "0335-7774433",
    },
    {
        "id": "paint_003",
        "name": "Premier Paint Works",
        "category": "painter",
        "area": "PECHS Block 6",
        "lat": 24.8694,
        "lng": 67.0635,
        "rating": 4.6,
        "availability": "today 3:00 PM",
        "on_time_score": 0.92,
        "cancellation_rate": 0.04,
        "review_count": 81,
        "specializations": ["Door Spray Polish", "Ceiling Paint"],
        "base_fee_pkr": 600,
        "per_hour_pkr": 300,
        "years_experience": 6,
        "phone": "0312-7778899",
    },
    {
        "id": "paint_004",
        "name": "Gulshan Color Experts",
        "category": "painter",
        "area": "Gulshan-e-Iqbal Block 7",
        "lat": 24.9253,
        "lng": 67.1005,
        "rating": 4.5,
        "availability": "tomorrow 09:00 AM",
        "on_time_score": 0.90,
        "cancellation_rate": 0.05,
        "review_count": 74,
        "specializations": ["Premium Wall Finish", "Wall Putty Repair"],
        "base_fee_pkr": 600,
        "per_hour_pkr": 300,
        "years_experience": 8,
        "phone": "0345-8889911",
    },
    {
        "id": "paint_005",
        "name": "North Nazimabad Painters",
        "category": "painter",
        "area": "North Nazimabad Block H",
        "lat": 24.9439,
        "lng": 67.0505,
        "rating": 4.4,
        "availability": "tomorrow 11:30 AM",
        "on_time_score": 0.89,
        "cancellation_rate": 0.05,
        "review_count": 62,
        "specializations": ["Interior Room Painting", "Cabinet Paint Touchups"],
        "base_fee_pkr": 500,
        "per_hour_pkr": 250,
        "years_experience": 5,
        "phone": "0300-4449900",
    },
    {
        "id": "paint_006",
        "name": "Surjani Fast Painters",
        "category": "painter",
        "area": "Surjani Town",
        "lat": 25.0165,
        "lng": 67.0416,
        "rating": 4.3,
        "availability": "today 5:00 PM",
        "on_time_score": 0.87,
        "cancellation_rate": 0.06,
        "review_count": 49,
        "specializations": ["Standard Room Paint", "Wall Patch Repair"],
        "base_fee_pkr": 400,
        "per_hour_pkr": 200,
        "years_experience": 4,
        "phone": "0313-2228899",
    },

    # ---- Tutors (5) ------------------------------------------------------------
    {
        "id": "tutor_001",
        "name": "EduStar Home Tutors",
        "category": "tutor",
        "area": "Clifton Block 8",
        "lat": 24.8207,
        "lng": 67.0254,
        "rating": 4.9,
        "availability": "tomorrow 04:00 PM",
        "on_time_score": 0.99,
        "cancellation_rate": 0.01,
        "review_count": 138,
        "specializations": ["O/A Level Mathematics", "Physics", "Chemistry"],
        "base_fee_pkr": 1500,
        "per_hour_pkr": 1000,
        "years_experience": 8,
        "phone": "0333-5554433",
    },
    {
        "id": "tutor_002",
        "name": "Bright Minds Academy",
        "category": "tutor",
        "area": "Gulshan-e-Iqbal Block 13",
        "lat": 24.9197,
        "lng": 67.1134,
        "rating": 4.7,
        "availability": "tomorrow 05:00 PM",
        "on_time_score": 0.96,
        "cancellation_rate": 0.02,
        "review_count": 97,
        "specializations": ["Metric/FSc Mathematics", "Computer Science"],
        "base_fee_pkr": 1000,
        "per_hour_pkr": 600,
        "years_experience": 6,
        "phone": "0312-8882211",
    },
    {
        "id": "tutor_003",
        "name": "Excel Tutoring Services",
        "category": "tutor",
        "area": "PECHS Block 2",
        "lat": 24.8654,
        "lng": 67.0590,
        "rating": 4.8,
        "availability": "today 6:00 PM",
        "on_time_score": 0.98,
        "cancellation_rate": 0.02,
        "review_count": 115,
        "specializations": ["Primary School Science", "English Language Classes"],
        "base_fee_pkr": 800,
        "per_hour_pkr": 500,
        "years_experience": 5,
        "phone": "0322-9993322",
    },
    {
        "id": "tutor_004",
        "name": "Tariq Road Home Lessons",
        "category": "tutor",
        "area": "Tariq Road",
        "lat": 24.8638,
        "lng": 67.0653,
        "rating": 4.6,
        "availability": "tomorrow 03:00 PM",
        "on_time_score": 0.94,
        "cancellation_rate": 0.03,
        "review_count": 78,
        "specializations": ["O Level Economics", "Accounting"],
        "base_fee_pkr": 1200,
        "per_hour_pkr": 800,
        "years_experience": 7,
        "phone": "0300-7771122",
    },
    {
        "id": "tutor_005",
        "name": "Nazimabad Academic Support",
        "category": "tutor",
        "area": "North Nazimabad Block J",
        "lat": 24.9476,
        "lng": 67.0549,
        "rating": 4.4,
        "availability": "tomorrow 04:30 PM",
        "on_time_score": 0.92,
        "cancellation_rate": 0.04,
        "review_count": 51,
        "specializations": ["Grade 1-8 General Subjects", "Science Tutoring"],
        "base_fee_pkr": 800,
        "per_hour_pkr": 400,
        "years_experience": 4,
        "phone": "0346-5559988",
    },

    # ---- Beauticians (5) -------------------------------------------------------
    {
        "id": "beauty_001",
        "name": "Glamour Touch Studio",
        "category": "beautician",
        "area": "DHA Phase 6",
        "lat": 24.7920,
        "lng": 67.0645,
        "rating": 4.8,
        "availability": "tomorrow 11:00 AM",
        "on_time_score": 0.96,
        "cancellation_rate": 0.02,
        "review_count": 167,
        "specializations": ["Bridal Makeup", "Facial Treatment", "Hairstyling"],
        "base_fee_pkr": 2000,
        "per_hour_pkr": 1200,
        "years_experience": 9,
        "phone": "0331-4442211",
    },
    {
        "id": "beauty_002",
        "name": "Beauty Bliss Salon",
        "category": "beautician",
        "area": "Clifton Block 5",
        "lat": 24.8090,
        "lng": 67.0307,
        "rating": 4.7,
        "availability": "tomorrow 02:00 PM",
        "on_time_score": 0.93,
        "cancellation_rate": 0.03,
        "review_count": 129,
        "specializations": ["Party Makeup", "Waxing & Threading", "Manicure & Pedicure"],
        "base_fee_pkr": 1500,
        "per_hour_pkr": 800,
        "years_experience": 6,
        "phone": "0323-8884433",
    },
    {
        "id": "beauty_003",
        "name": "Radiance Beauty",
        "category": "beautician",
        "area": "Bahadurabad",
        "lat": 24.8787,
        "lng": 67.0639,
        "rating": 4.6,
        "availability": "today 2:00 PM",
        "on_time_score": 0.91,
        "cancellation_rate": 0.05,
        "review_count": 84,
        "specializations": ["Mehndi Design", "Facial Glow Treatment", "Hair Coloring"],
        "base_fee_pkr": 1200,
        "per_hour_pkr": 700,
        "years_experience": 5,
        "phone": "0345-9992211",
    },
    {
        "id": "beauty_004",
        "name": "Gulshan Glam Salon",
        "category": "beautician",
        "area": "Gulshan-e-Iqbal Block 7",
        "lat": 24.9253,
        "lng": 67.1005,
        "rating": 4.5,
        "availability": "tomorrow 10:30 AM",
        "on_time_score": 0.90,
        "cancellation_rate": 0.04,
        "review_count": 99,
        "specializations": ["Hair Styling", "Face Cleanup", "Thread & Pluck"],
        "base_fee_pkr": 1000,
        "per_hour_pkr": 500,
        "years_experience": 7,
        "phone": "0300-9993322",
    },
    {
        "id": "beauty_005",
        "name": "Malir Beauty Parlour",
        "category": "beautician",
        "area": "Malir Cantonment",
        "lat": 24.8936,
        "lng": 67.2002,
        "rating": 4.4,
        "availability": "tomorrow 03:00 PM",
        "on_time_score": 0.88,
        "cancellation_rate": 0.06,
        "review_count": 48,
        "specializations": ["Facial Glow", "Simple Blowdry", "Nail Paint Art"],
        "base_fee_pkr": 1000,
        "per_hour_pkr": 600,
        "years_experience": 4,
        "phone": "0315-1114422",
    },
]
